Repository goedemiddag/laravel-autodiscovery-lock, pull requests merged in 2022-12, with the labels that each got.

#20 Upgrade to PHP 8.1
  .github/workflows/ci.yml
  composer.json
  rector.php
  src/Autodiscovery/LaravelPackageManifest.php
  src/Autodiscovery/ResolveResult.php
  src/Commands/AutodiscoveryPackageLock.php
  src/Commands/AutodiscoveryPackageLockVerify.php
Labels: enhancement

#24 Add property promotion
  composer.json
  src/Autodiscovery/ResolveResult.php
  src/Commands/AutodiscoveryPackageLock.php
  src/Commands/AutodiscoveryPackageLockVerify.php
Labels: enhancement, 2.0.0

#26 feat: contributing guide
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#28 Add config file for path and file name of lock file
  composer.json
  config/autodiscovery.php
  src/Autodiscovery/AutodiscoveryLockServiceProvider.php
  src/Autodiscovery/LaravelPackageManifest.php
  src/Commands/AutodiscoveryPackageLock.php
  src/Commands/AutodiscoveryPackageLockVerify.php
  src/Factories/LaravelPackageManifestFactory.php
  tests/Autodiscovery/AutoDiscoveryLockResolverTest.php
  tests/Autodiscovery/ResolveResultTest.php
  tests/Factories/LaravelPackageManifestFactoryTest.php
  tests/TestCase.php
Labels: enhancement
